### ISSUE TITLE
jte questions

### ISSUE THREAD

**Issue by 2x2xplz** [casid/jte-website#1]
Hello, thank you for jte, it's terrific. Now that I am using it more I have a bunch of questions. Some very simple and others a little more complex. I don't want to create a bunch of new issues on GitHub, are there any ways to contact you -- Kotlin Discord, email, StackOverflow, something else? I visited your game's website (cool!) but didn't see any contact info there either. I want to respect your privacy if you'd prefer to keep everything on GitHub, I just don't want to flood the project with new "issues" that are really just questions. Thank you!

**Comment by casid** [comment]
Welcome @2x2xplz, and thank you for the heads up! Very happy that you enjoy jte. In case you think your questions could be interesting for other users, I‘d say posting them as issues on the jte GitHub would be great!

In case there‘s stuff you don‘t want to be public, you can reach me at andy at mazebert.com 👍

I‘m currently on vacation so probably answers gonna be little delayed. But will be back home end of this week!
